yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models import UniqueConstraint
# Create your models here.


User = get_user_model()


class CreatedModel(models.Model):
    text = models.TextField('Текст', max_length=1000)

    class Meta:
        abstract = True


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(CreatedModel):
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True,
        db_index=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True,
                              null=True, related_name='group_posts',
                              verbose_name='Группа',
                              help_text=('Группа нового поста')
                              )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self) -> str:
        return self.text[:15]


class Comment(CreatedModel):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             blank=True,
                             null=True,
                             related_name='comments'
                             )
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='comments'
                               )
    created = models.DateTimeField('Дата написания', auto_now_add=True)

    class Meta:
        ordering = ['-created']

    def __str__(self) -> str:
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='follower'
                             )
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='following'
                               )

    class Meta:
        constraints = [
            UniqueConstraint(fields=['author', 'user'], name='unique_follow')
        ]

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('text', 'group', 'image')
        help_texts = {
            'text': 'Текст нового поста',
        }

    def not_empty_text(self):
        data = self.cleaned_data['text']
        if data == '':
            raise forms.ValidationError(
                'Кажется, все-таки нужно что-нибудь написать.')
        return data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        help_text = {
            'text': 'Текст нового комментария'
        }

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth import get_user_model
from .models import Post, Group, Follow
from .forms import CommentForm, PostForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page


User = get_user_model()
POSTS = 10
LIMIT_PAGE = 10


def pagination(request, post_list):
    paginator = Paginator(post_list, LIMIT_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


@cache_page(20)
def index(request):
    post_list = Post.objects.all()[:POSTS]
    title = 'Последние обновления на сайте'
    text = "Это главная страница проекта Yatube"
    page_obj = pagination(request, post_list)
    context = {
        'title': title,
        'text': text,
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.group_posts.all()[:POSTS]
    page_obj = pagination(request, posts)
    title = 'Записи сообщества'
    text = "Здесь будет информация о группах проекта Yatube"
    context = {
        'group': group,
        'page_obj': page_obj,
        'title': title,
        'text': text
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    post = (user.posts.select_related('group', 'author')
            .filter(author__username=username))[:POSTS]
    post_number = user.posts.count()
    page_obj = pagination(request, post)
    following = user.following.exists()
    context = {
        'page_obj': page_obj,
        'author': user,
        'post_number': post_number,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    post_num = post.author.posts.count()
    context = {
        'post': post,
        'post_num': post_num,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, files=request.FILES)

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect(f'/profile/{request.user}/')
        return render(request, 'posts/create_post.html', {'form': form})
    form = PostForm()
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author == request.user:
        if request.method == 'POST':
            form = PostForm(request.POST or None,
                            files=request.FILES or None,
                            instance=post)
            if form.is_valid():
                form.save()
                return redirect(f'/posts/{post_id}/')

        if request.method == 'GET':
            form = PostForm(instance=post)
            context = {
                'form': form,
                'is_edit': True,
                'post': post,
            }
            return render(request, 'posts/create_post.html', context)

        form = PostForm()
        context = {
            'form': form,
            'is_edit': True,
            'post': post,
        }
        return render(request, 'posts/create_post.html', context)

    return redirect(f'/posts/{post_id}/')


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    # информация о текущем пользователе доступна в переменной request.user
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = pagination(request, posts)
    context = {
        'page_obj': page_obj,
        'title': 'Посты ваших любимых авторов'
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    # Подписаться на автора
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    get_object_or_404(Follow, user=request.user, author=author).delete()
    return redirect('posts:follow_index')

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
<title>Новый пост</title> 
{% endblock %}
{%block content%}   
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">  
          {% if is_edit %}     
          Редактировать запись
          {% else %}
          Добавить запись
          {% endif %}             
        </div>
        <div class="card-body">        
          <form method="POST" action="" enctype="multipart/form-data">
            {% csrf_token %}           
            <div class="form-group row my-3 p-3">
              <label for="id_text">
                Текст поста                  
                <span class="required text-danger" >*</span>                  
              </label>
              {{form.text|addclass:'form-control'}}
              <small id="id_text-help" class="form-text text-muted">
                Текст нового поста
              </small>                  
            </div>            
            <div class="form-group row my-3 p-3">
              <label for="id_group">
                Группа                  
              </label>
                {{form.group|addclass:'form-control'}}
              <small id="id_group-help" class="form-text text-muted">
                Группа, к которой будет относиться пост
              </small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_image">
                Фотография поста                 
              </label>
              {{form.image|addclass:'form-control'}}
              <small id="id_image-help" class="form-text text-muted">
                Загрузите фотографию поста
              </small>
            </div>
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}     
                Сохранить
                {% else %}
                Добавить
                {% endif %} 
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{%endblock%}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}
{% block content %}
{%load thumbnail%}
<!-- класс py-5 создает отступы сверху и снизу блока -->
{% block title %}
<title>{{title}}</title> 
{% endblock %}
<div class="container py-5">     
  <h1>{{title}}</h1>
  <p>
    <a>{{text}}</a>
  </p>
  <article>
    {% cache 20 index_page %}
    {% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text }}</p>  
  {% if post.group %}   
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %} 
  <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
  {% endcache %} 
  </article>
  <!-- под последним постом нет линии -->
  {% include 'includes/paginator.html' %}
</div>  
{%endblock%}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} {{ group.title }} {% endblock %}
{% block content %}
<div class="container py-5">     
  <h1>{{ group.title }}</h1>
  <p>
    {{ group.description }}
  </p>
  <article>
    {% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
      <a href="{% url 'posts:profile' post.author %}">Все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text }}</p> 
  <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
  {% include 'includes/paginator.html' %}
  </article>
  <!-- под последним постом нет линии -->
</div> 
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% block content %}
{%load thumbnail%}
<!-- класс py-5 создает отступы сверху и снизу блока -->
{% block title %}
<title>{{title}}</title> 
{% endblock %}
<div class="container py-5">     
  <h1>{{title}}</h1>
  <p>
    <a>{{text}}</a>
  </p>
  <article>
    {% cache 20 index_page %}
    {% include 'posts/includes/switcher.html' %}
    {% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text }}</p>  
  {% if post.group %}   
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %} 
  <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
  {% endcache %} 
  </article>
  <!-- под последним постом нет линии -->
  {% include 'includes/paginator.html' %}
</div>  
{%endblock%}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  <title>Пост: {{ post.text|truncatechars:30 }}</title> 
{% endblock %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{post.pub_date|date:"d E Y"}}
        </li>
        <!-- если у поста есть группа -->   
        {% if post.group %}
        <li class="list-group-item">
          Группа: {{ post.group.slug }}
          <a href="{% url 'posts:group_list' post.group.slug %}">
            все записи группы
          </a>
        </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{post.author.get_full_name}}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:<span >{{post_num}}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{post.text}}
      </p>
      {% if post.author%}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">редактировать</a>
      {%endif%}
      {% load user_filters %}

      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'posts:add_comment' post.id %}">
              {% csrf_token %}      
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}

      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a href="{% url 'posts:profile' comment.author.username %}">
                {{ comment.author.username }}
              </a>
            </h5>
            <p>
              {{ comment.text }}
            </p>
          </div>
        </div>
      {% endfor %} 
    </article>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
<title>Профайл пользователя {{ author.get_full_name }}</title> 
{% endblock %}
    <!-- Подключены иконки, стили и заполенены мета теги -->
{% block content %}
<div class="container py-5">        
  <h1>Все посты пользователя {{ author.get_full_name }} <!--Лев Толстой--> </h1>
  <h3>Всего постов: {{post_number}} </h3>   
  {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
  {% endif %}
  {% for post in page_obj%}
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }} <!--Лев Толстой-->
        <a href="{% url 'posts:profile' post.author %}">Все посты пользователя</a>
      </li>
      <li>
        Дата публикации: {{post.pub_date|date:"d E Y"}} <!-- 31 июля 1854 --> 
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>
    {{ post.text }}
    </p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
  </article>       
  {% if post.group %}   
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}        
  {% if not forloop.last %}<hr>{% endif %}
  <!-- Остальные посты. после последнего нет черты -->
  <!-- Здесь подключён паджинатор -->  
  {% endfor %}
  {% include 'includes/paginator.html' %}
</div>
{% endblock %}